### ISSUE TITLE
README: JTFスタイルガイドとCCライセンスの素敵な関係リンク切れ

### ISSUE THREAD

**Issue by massongit** [textlint-ja/textlint-rule-preset-JTF-style#138]
https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/15e30bbc54e6678f947459081cdc8c97d08e9c18/README.md?plain=1#L754

上記がリンク切れになっているようです。

**Comment by azu** [comment]
[スタイルガイド｜JTF　日本翻訳連盟](https://www.jtf.jp/tips/styleguide)
3.0だとCC-BYになってるので、現状だとアーカイブのリンクを参照する感じになりそうですね

**Comment by massongit** [comment]
https://web.archive.org/web/20160323205055/http://journal.jtf.jp/update/id=306
WebArchiveで参照するのであれば上記あたりになりそうですね。

あるいは、 https://webjournal.jtf.jp/back-number/ にてWebカタログ形式で参照は可能なようなので、MLAスタイル等の論文引用のスタイルに則って何月号の何ページに記載されているかを載せるのもありかと思います。
