### ISSUE TITLE
2.2.2: 「11種類」が「1一種類」に修正されてしまう

### ISSUE THREAD

**Issue by superbrothers** [textlint-ja/textlint-rule-preset-JTF-style#65]
**問題:**

「2.2.2 算用数字と漢数字の使い分け」で「11種類」が慣用句の「一種」と判断されてしまうことで、「1一種類」と修正されてしまいます。

**期待する結果:**

「11種類」のまま変更されない。

**再現手順:**

```
$ echo 11種類 > index.md
$ npm install textlint@11.2.1 textlint-rule-preset-jtf-style@2.3.2
$ $(npm bin)/textlint --preset textlint-rule-preset-jtf-style index.md --fix --dry-run -f diff

/tmp/tmp.pmxgOAbbWv/index.md
- 11種類
+ 1一種類


✔ Fixed 1 problem
```

**Comment by azu** [comment]
なるほど `一種` の判定が誤検知しているのが原因みたいですね。
`1種[助詞]` に制限するのが安全そうですね

https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/174187a29631bafcfd7cddadb82e8dbeb43406f8/src/2.2.2.js#L186

**Comment by azu** [comment]
[v2.3.3](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/releases/tag/2.3.3)で修正しました。
ご確認ください。

**Comment by superbrothers** [comment]
v2.3.3 にアップグレードし修正されていることを確認しました。ありがとうございます！🎉
