### ISSUE TITLE
4.3.1: 半角の開きかっこと閉じかっこのうち、後者しか全角に修正されない

### ISSUE THREAD

**Issue by massongit** [textlint-ja/textlint-rule-preset-JTF-style#74]
開きかっこと閉じかっこがともに半角の丸かっこになっている文章を修正した場合、  両方とも全角になるのが正しいですが、実際には閉じかっこしか全角になりません。

<適用されるルール>
4.3.1.丸かっこ（）

<対象の文章>

https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/example/README.md

```
(npm 2.x以上をインストールしている必要があります)
```

<期待される修正結果>

```
（npm 2.x以上をインストールしている必要があります）
```

<実際の修正結果>

```
(npm 2.x以上をインストールしている必要があります）
```

**Comment by azu** [comment]
最初にマッチした片方しかreportしてないため、片方だけfixされているようです。
両方をreportして、両方をfixすれば修正できそうな気がします。
https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/3046ca91cd03d4ff78b89e06cbe898d577252a75/src/4.3.1.js#L36-L42

:memo: ワークアラウンドとして、カッコが対となってないパターンを見つける[@textlint-rule/textlint-rule-no-unmatched-pair](https://github.com/textlint-rule/textlint-rule-no-unmatched-pair)というルールも補助的に使えますね

**Comment by azu** [comment]
[v2.3.5](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/releases/tag/v2.3.5)で修正済みであるためクローズします。
