### ISSUE TITLE
かっこ と スペースに関するルールの修正とオプションの追加 3.3と4.3.1

### ISSUE THREAD

**Issue by azu** [textlint-ja/textlint-rule-preset-JTF-style#81]
## やること

- [ ] [4.3.1.丸かっこ（）](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/4.3.1.js) で かっこの内側または外側が日本語以外を含む、例外として半角かっこをエラーにしない
  - 現在は片方に隣接する日本語にマッチしているので不完全
- [ ] [3.3. かっこ類と隣接する文字の間のスペースの有無](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/3.3.js) の実装を 半角かっこ も検知するように修正する
- [ ] [3.3. かっこ類と隣接する文字の間のスペースの有無](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/3.3.js) に 半角かっこのときに外側のスペースを許容するというオプションを作成 (`allowOutsideHalfParentheses`) する
- [ ] [3.3. かっこ類と隣接する文字の間のスペースの有無](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/3.3.js) に 半角かっこのときに外側のスペースを必須にするというオプションを作成 (`requireOutsideHalfParentheses`) する
- [3.3. かっこ類と隣接する文字の間のスペースの有無](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/3.3.js) で 半角かっこのときに外側のスペースを許容するというオプション(`allowOutsideHalfParentheses`) をデフォルト値に設定

cc @smikitky @massongit

_Originally posted by @azu in https://github.com/textlint-ja/textlint-rule-preset-JTF-style/issues/79#issuecomment-703054375_

**Comment by frozenbonito** [comment]
@azu 
この Issue に取り組みたいと思っています。

> [3.3. かっこ類と隣接する文字の間のスペースの有無](https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/src/3.3.js) に 半角かっこのときに外側のスペースを許容するというオプションを作成 (allowOutsideHalfParentheses) する

こちらについて、下記 2 点確認させていただけないでしょうか。

1. https://github.com/textlint-ja/textlint-rule-preset-JTF-style/issues/79#issuecomment-703054375 を拝見しましたが、`Page(s)` のようなケースを考えると「括弧の外側が日本語の場合のみ外側のスペースを必須とする」のが良いと思うのですがいかがでしょうか。英文では `()` の外側のスペースを強制できなくなりますが、こちらは日本語のルールなので問題にならないと思っています。
    - OK: `Page(s)`
    - OK: `あああ (いいい) ううう`
    - NG: `あああ(いいい)ううう` 
2. 括弧の外側のスペースは半角スペースでも全角スペースでも許容されるでしょうか。fix に対応する場合はどちらを使って修正するのが望ましいでしょうか。

**Comment by azu** [comment]
ちょっと記憶が怪しいですが、JTFの元のルールが、スペースを入れないというルールだと思います。

> 3.3. かっこ類と隣接する文字の間のスペースの有無
> かっこの外側、内側ともにスペースを入れません。
> https://github.com/textlint-ja/textlint-rule-preset-JTF-style/blob/master/jtf_style_guide2.2.pdf

また原則としては半角記号を使わないとなってるので、半角を例外的に使いたい場合にどうするかが難しい感じですね。

<img width="877" alt="image" src="https://github.com/user-attachments/assets/94ccfd69-5a75-464c-bcc1-fd3d5d80c3ff">

```
OK: Page(s)
```

これは常にOKでも良い気はしています、それ以外の半角を使う場合はJTFに定義がないため、正解というのがなくてオプションにするしかない感じなんですよね。

**Comment by frozenbonito** [comment]
すみません、上記の質問に誤りがありました。

正しくは `allowOutsideHalfParentheses` ではなく「半角かっこのときに外側のスペースを**必須**にするオプション (`requireOutsideHalfParentheses`)」の方でした。

こちらを実装するとしたら、その挙動がどうあるべきかについてご相談したいです。

> 1. https://github.com/textlint-ja/textlint-rule-preset-JTF-style/issues/79#issuecomment-703054375 を拝見しましたが、Page(s) のようなケースを考えると「括弧の外側が日本語の場合のみ外側のスペースを必須とする」のが良いと思うのですがいかがでしょうか。英文では () の外側のスペースを強制できなくなりますが、こちらは日本語のルールなので問題にならないと思っています。
    - OK: Page(s)
    - OK: あああ (いいい) ううう
    - NG: あああ(いいい)ううう
> 2. 括弧の外側のスペースは半角スペースでも全角スペースでも許容されるでしょうか。fix に対応する場合はどちらを使って修正するのが望ましいでしょうか。

**Comment by frozenbonito** [comment]
@azu 
こちらの Proposal を実装する Pull Request (#127) を作成してみました。
お手隙の際にお目通しいただければ幸いです。
