### ISSUE TITLE
2.2.2 算用数字と漢数字の使い分け について

### ISSUE THREAD

**Issue by SGThr7** [textlint-ja/textlint-rule-preset-JTF-style#82]
```js
matchToReplace(text, /数([0-9]+)倍/g, toKanNumber);
matchToReplace(text, /数([0-9]+)[兆億万]/g, toKanNumber);
matchToReplace(text, /数([0-9]+)年/g, toKanNumber);
```

このルールはおそらく`数10倍`などを`数十倍`に訂正するためのものだと思います。
ですが、`周波数2倍ごと〜`といった文脈の場合にもエラーが出てしまいます。
また、漢数字を使う`数n倍`というような言い回しは、`n`が`10の倍数`の時しか起きないと思います。
例えば、`数十倍`・`数百倍`といった言い回しはありますが、`数二倍`というような言い回しはまず見ません。
したがって、以下のような修正が適当だと考えられますがいかがでしょうか。

```js
matchToReplace(text, /数(10*)倍/g, toKanNumber);
matchToReplace(text, /数(10*)[兆億万]/g, toKanNumber);
matchToReplace(text, /数(10*)年/g, toKanNumber);
```

**Comment by azu** [comment]
たしかに、"数n倍" は 単に "n倍" という気がするので一桁の値を除外するのは、よさそうな気がしますね。

**Comment by azu** [comment]
Fixed in https://github.com/textlint-ja/textlint-rule-preset-JTF-style/releases/tag/v2.3.7

**Comment by azu** [comment]
@SGThr7 対応ありがとうございます！
